### ISSUE TITLE
Categorize talks from AAS 223, 225

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/Gender-in-Astro#10]
This was one of the things I _really_ wanted to work on this year, and am so glad people put in the effort to group all the sessions at AAS 227 in to a handful of categories!

Would the same folks be willing to do the same with AAS 223, and AAS 225? I can dig up the old programs, etc, if needed?

Also: can we add this as a table for each conference in the `data` directory?

**Comment by willettk** [comment]
I think that'd be great. I agree should move the data contained in the iPython notebook from 5a92d086f52185cad1a9a2faba980203d67e8c0f as a separate file in `data`. 

Before pushing forward on doing previous conferences - are you happy with the classifications that J'Neil and Holly used for AAS 227? I think they're good - the six categories of astro-ph, plus an additional catch-all for education, outreach, etc., but we should decide if this will be the final version before starting on other conferences. 
1. Galaxies: Galaxies, including the Milky Way, and their contents. Galactic structure and evolution, objects within galaxies, ISM ,clouds, and dust.
2. Cosmology: Non-galactic cosmology including CMB, extragalactic distance scale, intergalactic medium, large-scale structure of the universe, particle astrophysics.
3. High Energy: Cosmic rays, gamma and x-ray astronomy, supernovae, black holes, AGN, neutron stars, pulsars.
4. Earth/Planetary: Astrobiology, exoplanet detection and properties, structure and formation of the solar system.
5. Solar/Stellar: Star formation, binary systems, white and brown dwarfs, stellar evolution and structures.
6. Methods: Data analysis, statistics, catalogs, surveys, instrumentation, and software.
7. Education, Outreach, and Professional Development: History of astronomy, astronomy education research, public outreach, teaching practices, and methodology lectures. Includes all plenary sessions and town halls.

I think these are good, but I'm not sure about including the plenary sessions and town halls in the last one - I'd vote for categorizing them by content in the first six categories, rather than format.

**Comment by jradavenport** [comment]
I agree, putting Plenary talks (and maybe town halls) in to subject-appropriate categories.

**Comment by jradavenport** [comment]
Attn: @jneilcottle @hmchristenson

Let's meet on Friday at 2pm to discuss this!

**Comment by astrojneil** [comment]
I have class at 2! Can we meet at 1:00 or 3:00?

**Comment by jradavenport** [comment]
3:00 works for me! @hmchristenson ?

**Comment by hmchristenson** [comment]
3:00 is good!

**Comment by stephtdouglas** [comment]
It looks like this is done for AAS 225. 

I found the AAS 223 abstracts (https://files.aas.org/aas223/AAS_223_Abstracts.pdf), but I'm going to close this issue and incorporate this task into #17
